### ISSUE TITLE
打包app时node内存溢出

### ISSUE THREAD

**Issue by qiqiblog** [yinxin630/fiora-app#10]
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200927.141554.3510.0.001.json

Node.js report completed
 1: 0x9ef190 node::Abort() [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
 2: 0x9f13b2 node::OnFatalError(char const*, char const*) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]

 3: 0xb5da9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
 4: 0xb5de19 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
 5: 0xd0a765  [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
 6: 0xd0adf6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
 7: 0xd1760a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
 8: 0xd18515 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
 9: 0xd1afcc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
10: 0xce19bb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
11: 0x10246ce v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]
12: 0x13a71b9  [/usr/local/lighthouse/softwares/nodejs/node-v12.16.1-linux-x64/bin/node]

socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by yinxin630** [comment]
你是在服务器上打包的么

**Comment by qiqiblog** [comment]
> 你是在服务器上打包的么

是的

**Comment by yinxin630** [comment]
这个在自己电脑上打包就行

**Comment by qiqiblog** [comment]
> 这个在自己电脑上打包就行

自己电脑上也报错
