### ISSUE TITLE
网站正常，但是自行编译安卓APP后显示连接服务端失败怎么办

### ISSUE THREAD

**Issue by lteyox** [yinxin630/fiora-app#11]
# 网站正常，但是自行编译安卓APP后显示连接服务端失败怎么办
网站链接:https://chat.lteyox.top
用的是bt反向代理

**Comment by lteyox** [comment]
通过端口访问[http://chat.lteyox.top:2900](url)，连接上了但是所有图片无法加载求解

**Comment by yinxin630** [comment]
这个得 debug 看看, 请求的图片地址是什么, 然后结合实际地址推测下出问题的地方

用开发模式跑 app 源码, 或者 Charles 抓包看看图片链接

**Comment by yinxin630** [comment]
Closed with not been updated for too long
