### ISSUE TITLE
安卓版本的链接失效惹

### ISSUE THREAD

**Issue by kirainl** [yinxin630/fiora-app#2]
http://cdn.suisuijiang.com/fiora-v0.2.3.apk
这个链接无法下载呢～

**Comment by yinxin630** [comment]
链接已经换了, 最新链接以web端左侧APP按钮为准
新链接: <https://cdn.suisuijiang.com/fiora.apk?v=1563759471515>

**Comment by MuenYu** [comment]
现在也是失效状态呢
